# Generated by Django 3.1 on 2021-03-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='platename',
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_no',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
