# Generated by Django 3.1 on 2021-03-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210303_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
