# Generated by Django 3.1 on 2021-03-04 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_product_url_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transaction_no',
        ),
    ]
