# Generated by Django 3.1 on 2021-01-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_product_digital'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='charector_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
