# Generated by Django 3.1 on 2021-01-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_remove_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='charector_price',
        ),
        migrations.AddField(
            model_name='product',
            name='charector',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
