# Generated by Django 3.1 on 2021-01-18 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20210115_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='charector',
            new_name='ch',
        ),
    ]
