# Generated by Django 3.1 on 2021-01-18 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
