# Generated by Django 3.1 on 2021-01-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_remove_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charprice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='ch',
            new_name='char_price',
        ),
    ]
