# Generated by Django 3.1 on 2021-01-19 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20210119_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ch_price',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='char_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.charprice'),
        ),
    ]
