# Generated by Django 3.1 on 2021-01-19 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20210119_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ch_price',
            new_name='per_ch_price',
        ),
    ]
