# Generated by Django 3.1 on 2021-01-19 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20210119_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='per_ch_price',
            new_name='ch_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='charprice',
            new_name='char_price',
        ),
    ]
