# Generated by Django 3.1 on 2021-01-19 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20210119_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='char_price',
            new_name='charprice',
        ),
    ]
