# Generated by Django 3.1 on 2021-01-19 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20210119_1152'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Charprice',
            new_name='Charector',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='charprice',
            new_name='charector',
        ),
    ]
