# Generated by Django 3.1 on 2021-01-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_auto_20210119_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charector',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
