# Generated by Django 3.1 on 2021-01-21 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_auto_20210119_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charector',
            name='total',
        ),
    ]
