# Generated by Django 3.1 on 2021-01-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_remove_charector_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
