# Generated by Django 3.1 on 2021-01-22 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_product_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='count',
        ),
    ]
