# Generated by Django 3.1 on 2021-01-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_remove_product_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='platename',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
