# Generated by Django 3.1 on 2021-01-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_product_platename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.IntegerField(null=True),
        ),
    ]
