# Generated by Django 3.1 on 2021-01-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_auto_20210122_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='charector',
            name='chtotal',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
