# Generated by Django 3.1 on 2021-01-22 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_charector_chtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charector',
            name='chtotal',
        ),
    ]
