# Generated by Django 3.1 on 2021-01-22 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_remove_charector_chtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='charector',
        ),
        migrations.AddField(
            model_name='charector',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.product'),
        ),
        migrations.AddField(
            model_name='charector',
            name='total',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
