# Generated by Django 3.1 on 2021-01-22 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_auto_20210122_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charector',
            name='total',
        ),
    ]
