# Generated by Django 3.1 on 2021-01-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_remove_charector_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='charector',
            name='total',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
