# Generated by Django 3.1 on 2021-01-22 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_charector_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charector',
            name='total',
        ),
    ]
