# Generated by Django 3.1 on 2021-01-28 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_auto_20210127_0726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charector',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='charector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.charector'),
        ),
    ]
