# Generated by Django 3.1 on 2021-01-28 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_auto_20210128_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='charector',
        ),
        migrations.AddField(
            model_name='charector',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.product'),
        ),
    ]
