# Generated by Django 3.1 on 2021-01-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0036_auto_20210128_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charector',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
